package UI;

import Estruturas.FilaBebidasPedido;
import Estruturas.Pedido;
import Estruturas.TipoBebida;
import static UI.GerenciaMaquina.ProcessaPedido;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public final class PedidoUI extends javax.swing.JFrame {

    /**
     * Creates new form Pedido
     */
    private final String nomeCliente;

    public PedidoUI(String nomeCliente) {
        initComponents();
        setLocationRelativeTo(null);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        URL url = getClass().getResource("Icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);

        //Altera o nome no texto para o do cliente
        this.nomeCliente = nomeCliente;
        txtOqueDeseja.setText(String.format(txtOqueDeseja.getText(), nomeCliente));
        
        //Atualiza as quantidades de bebidas na tela
        AtualizaQuantidadesTela();

    }

    public void AtualizaQuantidadesTela() {
        try {
            int qtdCafe = GerenciaMaquina.listaEstoque.getTipoBebida(TipoBebida.Cafe).size();
            int qtdCappuccino = GerenciaMaquina.listaEstoque.getTipoBebida(TipoBebida.Cappuccino).size();
            int qtdChocolate = GerenciaMaquina.listaEstoque.getTipoBebida(TipoBebida.Chocolate).size();
            int qtdCha = GerenciaMaquina.listaEstoque.getTipoBebida(TipoBebida.Cha).size();

            EstoqueQtdCafe.setText(String.format(EstoqueQtdCafe.getText(), qtdCafe));
            EstoqueQtdCappuccino.setText(String.format(EstoqueQtdCappuccino.getText(), qtdCappuccino));
            EstoqueQtdChocolate.setText(String.format(EstoqueQtdChocolate.getText(), qtdChocolate));
            EstoqueQtdCha.setText(String.format(EstoqueQtdCha.getText(), qtdCha));

            if (qtdCafe == 0) {
                PedidoQtdCafe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
            }
            if (qtdCappuccino == 0) {
                PedidoQtdCafe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
            }
            if (qtdChocolate == 0) {
                PedidoQtdCafe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
            }
            if (qtdCha == 0) {
                PedidoQtdCafe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foram encontradas bebidas: " + ex.getMessage(), "Alerta", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOqueDeseja = new javax.swing.JLabel();
        PedidoQtdCafe = new javax.swing.JSpinner();
        PedidoQtdChocolate = new javax.swing.JSpinner();
        PedidoQtdCappuccino = new javax.swing.JSpinner();
        PedidoQtdCha = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EstoqueQtdCafe = new javax.swing.JLabel();
        EstoqueQtdCappuccino = new javax.swing.JLabel();
        EstoqueQtdCha = new javax.swing.JLabel();
        EstoqueQtdChocolate = new javax.swing.JLabel();
        btnEnviarPedido = new javax.swing.JButton();
        iconXicaraCafe = new javax.swing.JButton();
        iconXicaraCafe1 = new javax.swing.JButton();
        iconXicaraCafe2 = new javax.swing.JButton();
        iconXicaraCafe3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cardápio - GustCoffee");

        txtOqueDeseja.setText("Olá %s! o que você deseja hoje? Veja nosso cardápio:");

        PedidoQtdCafe.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        PedidoQtdCafe.setToolTipText("Quantidade desejada de Café(s)");
        PedidoQtdCafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PedidoQtdCafe.setMaximumSize(new java.awt.Dimension(2, 2));

        PedidoQtdChocolate.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        PedidoQtdChocolate.setToolTipText("Quantidade desejada de Chocolate(s)");
        PedidoQtdChocolate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PedidoQtdCappuccino.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        PedidoQtdCappuccino.setToolTipText("Quantidade Desejada de Cappuccino(s)");
        PedidoQtdCappuccino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PedidoQtdCha.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        PedidoQtdCha.setToolTipText("Quantidade desejada de Chá(s)");
        PedidoQtdCha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("Café");

        jLabel3.setText("Cappuccino");

        jLabel4.setText("Chocolate");

        jLabel5.setText("Chá");

        EstoqueQtdCafe.setText("%d Disponíveis");

        EstoqueQtdCappuccino.setText("%d Disponíveis");

        EstoqueQtdCha.setText("%d Disponíveis");

        EstoqueQtdChocolate.setText("%d Disponíveis");

        btnEnviarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/avancar.png"))); // NOI18N
        btnEnviarPedido.setBorderPainted(false);
        btnEnviarPedido.setContentAreaFilled(false);
        btnEnviarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedidoActionPerformed(evt);
            }
        });

        iconXicaraCafe.setBackground(null);
        iconXicaraCafe.setForeground(null);
        iconXicaraCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/cafeIcon.png"))); // NOI18N
        iconXicaraCafe.setBorderPainted(false);
        iconXicaraCafe.setContentAreaFilled(false);

        iconXicaraCafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/cafeIcon.png"))); // NOI18N
        iconXicaraCafe1.setBorderPainted(false);
        iconXicaraCafe1.setContentAreaFilled(false);

        iconXicaraCafe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/cafeIcon.png"))); // NOI18N
        iconXicaraCafe2.setBorderPainted(false);
        iconXicaraCafe2.setContentAreaFilled(false);

        iconXicaraCafe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arquivos/cafeIcon.png"))); // NOI18N
        iconXicaraCafe3.setBorderPainted(false);
        iconXicaraCafe3.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PedidoQtdCha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconXicaraCafe3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstoqueQtdCha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PedidoQtdChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconXicaraCafe2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstoqueQtdChocolate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PedidoQtdCafe, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(PedidoQtdCappuccino))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(txtOqueDeseja))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iconXicaraCafe1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iconXicaraCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EstoqueQtdCafe)
                            .addComponent(EstoqueQtdCappuccino))))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnEnviarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOqueDeseja)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PedidoQtdCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(EstoqueQtdCafe))
                                    .addComponent(iconXicaraCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconXicaraCafe1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PedidoQtdCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))))
                            .addComponent(EstoqueQtdCappuccino))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PedidoQtdChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(EstoqueQtdChocolate)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(iconXicaraCafe2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PedidoQtdCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(EstoqueQtdCha)))
                    .addComponent(iconXicaraCafe3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEnviarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedidoActionPerformed
        try {
            int qtdCafe = (Integer) (PedidoQtdCafe.getValue());
            int qtdCappuccino = (Integer) PedidoQtdCappuccino.getValue();
            int qtdChocolate = (Integer) PedidoQtdChocolate.getValue();
            int qtdCha = (Integer) PedidoQtdCha.getValue();

            if (qtdCafe == 0 && qtdCappuccino == 0 && qtdChocolate == 0 && qtdCha == 0) {
                JOptionPane.showMessageDialog(this, "Por favor, escolha ao menos uma bebida :)", "Alerta", 3);
                return;
            }

            // Cria a fila de bebidas
            FilaBebidasPedido filaBebidas = new FilaBebidasPedido();

            if (qtdCafe > 0) {
                filaBebidas.enqueue(TipoBebida.Cafe, qtdCafe);
            }
            if (qtdCappuccino > 0) {
                filaBebidas.enqueue(TipoBebida.Cappuccino, qtdCappuccino);
            }
            if (qtdChocolate > 0) {
                filaBebidas.enqueue(TipoBebida.Chocolate, qtdChocolate);
            }
            if (qtdCha > 0) {
                filaBebidas.enqueue(TipoBebida.Cha, qtdCha);
            }

            //Cria um novo pedido com uma fila de bebidas para serem retiradas do estoque
            Pedido novo = new Pedido(nomeCliente, filaBebidas);

            JOptionPane.showMessageDialog(this, "Seu pedido foi enviado para preparo!!", "Informação", 3);

            ProcessaPedido(novo);
            
            JOptionPane.showMessageDialog(this, "Obrigado volte sempre! :)");
            this.setVisible(false);
            new Principal().setVisible(true);
            
            //Melhorar
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Por favor, escolha ao menos uma bebida :)", "Alerta", 3);
            System.out.println("Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnEnviarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PedidoUI pedido = new PedidoUI("");
                pedido.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstoqueQtdCafe;
    private javax.swing.JLabel EstoqueQtdCappuccino;
    private javax.swing.JLabel EstoqueQtdCha;
    private javax.swing.JLabel EstoqueQtdChocolate;
    private javax.swing.JSpinner PedidoQtdCafe;
    private javax.swing.JSpinner PedidoQtdCappuccino;
    private javax.swing.JSpinner PedidoQtdCha;
    private javax.swing.JSpinner PedidoQtdChocolate;
    private javax.swing.JButton btnEnviarPedido;
    private javax.swing.JButton iconXicaraCafe;
    private javax.swing.JButton iconXicaraCafe1;
    private javax.swing.JButton iconXicaraCafe2;
    private javax.swing.JButton iconXicaraCafe3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txtOqueDeseja;
    // End of variables declaration//GEN-END:variables
}
